require.config({
    baseUrl: '/Scripts',
    paths: {
        'jquery': 'lib/jquery-1.10.2.min',
        'jquery.validate': 'lib/jquery.validate.min',
        'jquery.maskedinput': 'lib/jquery.maskedinput.min',
        'jquery.unobtrusive': 'lib/jquery.validate.unobtrusive.min',
        'jquery.numeric': 'lib/jquery.numeric',
        'jquery.color': 'lib/jquery.color-2.1.0.min',
        'bootstrap': 'lib/bootstrap.min',
        'tooltip': 'lib/bootstrap-tooltip',
        'datepicker': 'lib/bootstrap-datepicker',
        'collapse': 'lib/bootstrap-collapse',
        'underscore': 'lib/underscore',
        'toastr': 'lib/toastr.min',
        'moment': 'lib/moment.min',
        'knockout': 'lib/knockout-2.2.1',
        'ko': 'app/customBindings',
        'bootbox': 'lib/bootbox.min',
        'text': 'lib/text',
        'highcharts': 'lib/highcharts',
        'typeahead': 'lib/typeahead.bundle.min',
        'bloodhound': 'lib/bloodhound.min',
        'handlebars': 'lib/handlebars.min',
        'x-editable': 'lib/bootstrap-editable.min',
        'responsive.tabs': 'lib/responsive.tabs',
        'ko.x-editable': 'lib/knockout.x-editable.min',
        'ko.validation': 'lib/knockout.validation.min',
        'hideseek': 'lib/jquery.hideseek.min',
        'maxlength': 'lib/bootstrap-maxlength.min',
        'polyfill': 'lib/polyfill.min',
        'main': 'app/main',
        'impersonateUser': 'app/impersonateUser'
    },
    shim: {
        'jquery.validate': ['jquery'],
        'jquery.unobtrusive': ['jquery.validate'],
        'bootstrap': ['jquery', 'jquery.validate', 'jquery.unobtrusive'],
        'tooltip': { deps: ['bootstrap'], exports: '$.fn.tooltip' },
        'datepicker': { deps: ['bootstrap'], exports: '$.fn.datepicker' },
        'collapse': { deps: ['bootstrap'], exports: '$.fn.collapse' },
        'x-editable': { deps: ['bootstrap'], exports: '$.fn.editable' },
        'underscore': { exports: '_' },
        'ko': ['underscore'],
        'ko.x-editable': ['ko'],
        'ko.validation': ['ko'],
        'highcharts': { deps: ['jquery'], exports: 'Highcharts' },
        'bloodhound': { deps: ['jquery'], exports: 'Bloodhound' },
        'responsive.tabs': { deps: ['bootstrap'] },
        'jquery.maskedinput': ['jquery'],
        'hideseek': ['jquery'],
        'maxlength': ['jquery'],
        'typeahead': ['jquery'],
    },
    deps: ['impersonateUser'],
    callback: function () {
        require(['app/feedbackForm', 'app/quickSearch', 'app/tooltips', 'app/ajaxEvents', 'app/dates', 'app/formInputs', 'app/toastrNotify', 'app/requiredFields', 'app/responsiveTabs', 'app/shared/keepAlive']);
    }
});
