CREATE TABLE lookups.ProblemCodes(
    ProblemCodeId INT NOT NULL IDENTITY(1,1),
    ProblemCode VARCHAR(250) NOT NULL
    CONSTRAINT PK_ProblemCodes
        PRIMARY KEY (ProblemCodeId)
)

INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Acrylic Decking')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Appliance Installation')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Appliances')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Block Labor')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Brick Labor')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Cabinet Material')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Cabinets/Install')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Cable/Phone Wiring')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Carpet')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Caulking')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Ceiling Fan')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Ceramic Tile Flooring')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Ceramic Tile Walls')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Ceramic Tile')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Cornice Labor')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Countertops Formica')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Countertops Granite')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Countertops Marble')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Countertops Silestone')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Countertops Solid Surface')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Deck')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Drywall')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Electrical')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Exterior Doors')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Exterior Trim/Siding')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Fence')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Final Grade')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Fire Sprinkler System')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Fireplace')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Flashing')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Flatwork')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Foundation')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Frame Labor')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Front Door')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Garage Doors/Opener')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Gas ')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Gutters and downspouts')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Hardware')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Hardwood Flooring')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('HBR5')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Heating/Air Conditioning')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Inspection Request')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Insulation')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Landscaping Shrubs')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Light Fixtures')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Mailbox')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Metal Roof')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Mirrors/Shower Doors')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Paint')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Pavers')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Pest Control')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Plumbing Leaks')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Plumbing')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Pool Equipment')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Question')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Retaining Wall')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Roof Leak')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Roof')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Security System')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Septic/Well Equipment')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Skylights')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Sod')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Sprinkler System')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Stairs')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Stone Labor & Turnkey')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Stucco')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Trees')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Trim Labor')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Trim Materials/Interior Doors')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Tub')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Vent-a-Hood')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Vinyl')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Wallpaper')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Warrantable')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Warranty Orientation')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Water Filtration System')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Weather stripping')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Window Treatment')
INSERT INTO lookups.ProblemCodes(ProblemCode) VALUES('Windows')
