CREATE TABLE imports.JobStage(
	JobStageId uniqueidentifier NOT NULL CONSTRAINT DF_Jobs_Id  DEFAULT (newsequentialid()),
	JobNumber varchar(8) NULL,
	CloseDate date NULL,
    StartDate date NULL,
    CompletionDate date NULL,
    SalesDate date NULL,
    StartPostDate date NULL,
	AddressLine varchar(255) NULL,
	City varchar(100) NULL,
	StateCode varchar(2) NULL,
	PostalCode varchar(15) NULL,
	LegalDescription varchar(100) NULL,
	CommunityNumber varchar(8) NULL,
    CommunityName varchar(100) NULL,
    CommunityMarketingName varchar(100) NULL,
	BuyerNumber varchar(8) NULL,
    BuyerName varchar(100) NULL,
    BuyerAddressLine varchar(255) NULL,
    BuyerCity VARCHAR(100) NULL,
    BuyerStateCode VARCHAR(2) NULL,
    BuyerPostalCode VARCHAR(15) NULL,
    BuyerEmail VARCHAR(255) NULL,
	PlanType varchar(3) NULL,
	PlanTypeDescription varchar(20) NULL,
	PlanName varchar(30) NULL,
	PlanNumber varchar(4) NULL,
	Elevation varchar(3) NULL,
	Swing varchar(20) NULL,
    Stage INT NULL,
	BuilderEmployeeNumber varchar(8) NULL,
	BuilderEmployeeName varchar(100) NULL,
	SalesConsultantEmployeeNumber varchar(8) NULL,
	SalesConsultantEmployeeName varchar(100) NULL,	
	TotalPrice decimal(15, 2) NULL,	
    JdeIdentifier VARCHAR(255) NULL,
    CONSTRAINT PK_JobStage
        PRIMARY KEY (JobStageId)
)
