CREATE TABLE lookups.RootCauses (
    RootCauseId TINYINT NOT NULL,
    RootCause VARCHAR(50) NOT NULL,
    CONSTRAINT PK_RootCauses
        PRIMARY KEY (RootCauseId)
);

INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 1, 'Adjustments')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 2, 'All')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 3, 'Appliance Leak')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 4, 'Attic Stairs')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 5, 'Backsplash / Countertops')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 6, 'Balance')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 7, 'Balance system')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 8, 'Bath')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 9, 'Breakers')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 10, 'Broken')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 11, 'Broken Seal')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 12, 'Cable not working')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 13, 'Ceiling')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 14, 'Chimney/ Flue/Caps')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 15, 'Chips')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 16, 'Clean')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 17, 'Cleaning')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 18, 'Columns')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 19, 'Commode')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 20, 'Commode Running')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 21, 'Computer Wiring')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 22, 'Cooling')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 23, 'Counter Flashing')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 24, 'Coverage')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 25, 'Crack')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 26, 'Cracked')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 27, 'Cracks')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 28, 'Crawl Space')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 29, 'Dead')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 30, 'Dead Shrubs')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 31, 'Defective Fixture')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 32, 'Delaminating')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 33, 'Door')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 34, 'Doorbell')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 35, 'Drain')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 36, 'Drain/Sewer Issue')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 37, 'Drainage')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 38, 'Drip edge')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 39, 'Duct Work')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 40, 'Electric Heater')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 41, 'Electrical')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 42, 'Electrical issue')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 43, 'Exterior')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 44, 'Exterior Lighting')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 45, 'Finish')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 46, 'Firebox Install')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 47, 'Firebox Material')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 48, 'Fireplace')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 49, 'Fireplace Surround Chip')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 50, 'Fireplace Surround Cracked')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 51, 'Fireplace Surround Grout')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 52, 'Fixture')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 53, 'Fixture Install')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 54, 'Fixture Issue')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 55, 'Flashing')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 56, 'Floor Squeaks')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 57, 'Freon / Water Leak')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 58, 'Grout')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 59, 'Hardi Siding')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 60, 'Hardware')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 61, 'Heat')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 62, 'HVAC equipment Leak')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 63, 'Improper Installation')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 64, 'Install')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 65, 'Installation')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 66, 'Installed Trees')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 67, 'Interior Door Adjustment')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 68, 'Interior Hardware Adjustment')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 69, 'Item Under Carpet')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 70, 'Jetted operation')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 71, 'Joint Separation')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 72, 'Leak')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 73, 'Leak Damage')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 74, 'Leaks')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 75, 'Mantle')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 76, 'Material')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 77, 'Material Issue')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 78, 'Mirrors')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 79, 'Missing')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 80, 'Missing Jack')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 81, 'Missing Manual')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 82, 'Missing Part')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 83, 'Missing Parts')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 84, 'Missing Piers')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 85, 'Missing Trim')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 86, 'One Year')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 87, 'Opener / Remotes')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 88, 'Operation')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 89, 'Operation / Adjustment')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 90, 'Operation/Adjustments')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 91, 'Original Trees')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 92, 'Other')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 93, 'Phone not working')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 94, 'Pilot Light')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 95, 'Plugs/Switches')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 96, 'Plumbing')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 97, 'Pressure')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 98, 'Pump')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 99, 'Railings')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 100, 'Re-glaze / Scratches')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 101, 'Re-Key')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 102, 'Re-stretch')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 103, 'Reglazes / Scratches')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 104, 'Roof/Decking')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 105, 'Scratches')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 106, 'Screen Enclosure')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 107, 'Screens')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 108, 'Sea Wall')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 109, 'Seam Issue')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 110, 'Settlement')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 111, 'Settlement/Failure')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 112, 'Shingle')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 113, 'Shingle/Tile')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 114, 'Shower Door Operation')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 115, 'Shutters')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 116, 'Smoke Detectors')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 117, 'Soap Dish')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 118, 'Specialty')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 119, 'Split Wood')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 120, 'Stained')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 121, 'Stairs')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 122, 'Standing Water')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 123, 'Step Flashing Leak')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 124, 'Stress Crack')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 125, 'Sub Floor')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 126, 'Supply Line and Other')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 127, 'Surround Sound')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 128, 'Thermostats')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 129, 'Tile')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 130, 'Top Soil')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 131, 'Torn')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 132, 'Trim')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 133, 'Tub/Shower Drainage')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 134, 'Tub/Shower Leak')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 135, 'Tubs/Showers')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 136, 'Underpinning')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 137, 'Uneven')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 138, 'Vent')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 139, 'Venting')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 140, 'Venting/Exhaust')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 141, 'Vinyl Siding')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 142, 'Walls')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 143, 'Warped')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 144, 'Warped Door')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 145, 'Warped Doors')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 146, 'Water Heater')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 147, 'Water Leak')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 148, 'Water Supply')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 149, 'Water Supply / Pressure')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 150, 'Weather Strip')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 151, 'Weep Holes')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 152, 'Windows/Doors Leak')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 153, 'Wiring')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 154, 'Wood Shelving')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 155, 'Workmanship / Finish')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 156, 'Wrong Door Installed')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 157, 'Wrong Model')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 158, 'Wrong Selection Installed')
INSERT INTO lookups.RootCauses (RootCauseId, RootCause) VALUES ( 159, 'Wrong Trim')