
DELETE [dbo].[ProblemCodes]

INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Acrylic Decking', 'ACD', 'Crack') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Acrylic Decking', 'ACD', 'Finish') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Acrylic Decking', 'ACD', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Appliance Installation', 'API', 'Electrical Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Appliance Installation', 'API', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Appliance Installation', 'API', 'Water Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Appliances', 'APP', 'Missing Manual') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Appliances', 'APP', 'Missing Part') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Appliances', 'APP', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Appliances', 'APP', 'Wrong Model') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Block Labor', 'BKL', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Brick Labor', 'BRL', 'Cleaning') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Brick Labor', 'BRL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Brick Labor', 'BRL', 'Settlement') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Brick Labor', 'BRL', 'Stress Crack') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cabinet Material', 'CAM', 'Finish') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cabinet Material', 'CAM', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cabinet Material', 'CAM', 'Warped Door') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cabinets/Install', 'CAB', 'Adjustments') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cabinets/Install', 'CAB', 'Hardware') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cabinets/Install', 'CAB', 'Improper Installation') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cabinets/Install', 'CAB', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cable/Phone Wiring', 'CPH', 'Cable Not Working') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cable/Phone Wiring', 'CPH', 'Computer Wiring') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cable/Phone Wiring', 'CPH', 'Missing Jack') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cable/Phone Wiring', 'CPH', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cable/Phone Wiring', 'CPH', 'Phone Not Working') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cable/Phone Wiring', 'CPH', 'Surround Sound') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Carpet', 'FLC', 'Cleaning') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Carpet', 'FLC', 'Item Under Carpet') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Carpet', 'FLC', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Carpet', 'FLC', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Carpet', 'FLC', 'Re-Stretch') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Carpet', 'FLC', 'Seam Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Caulk', 'CLK', 'Backsplash/Countertops') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Caulk', 'CLK', 'Exterior') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Caulk', 'CLK', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Caulk', 'CLK', 'Trim') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Caulk', 'CLK', 'Tubs/Showers') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceiling Fan', 'CFN', 'Balance') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceiling Fan', 'CFN', 'Improper Installation') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceiling Fan', 'CFN', 'Missing Part') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceiling Fan', 'CFN', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile', 'TIL', 'Cleaning') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile', 'TIL', 'Fireplace Surround Chip') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile', 'TIL', 'Fireplace Surround Cracked') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile', 'TIL', 'Fireplace Surround Grout') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile', 'TIL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile', 'TIL', 'Specialty') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Flooring', 'FCT', 'Chips') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Flooring', 'FCT', 'Cracked') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Flooring', 'FCT', 'Grout') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Flooring', 'FCT', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Walls', 'CTW', 'Chips') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Walls', 'CTW', 'Cracked') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Walls', 'CTW', 'Grout') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Walls', 'CTW', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Walls', 'CTW', 'Soap Dish') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Walls', 'CTW', 'Tub/Shower Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Walls', 'CTW', 'Tub/Shower Drainage') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Ceramic Tile Walls', 'CTW', 'Weep Holes') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cornice Labor', 'CRL', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Cornice Labor', 'CRL', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Formica', 'COF', 'Chips') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Formica', 'COF', 'Cracked') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Formica', 'COF', 'Delaminating') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Formica', 'COF', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Formica', 'COF', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Formica', 'COF', 'Seam Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Granite', 'COG', 'Chips') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Granite', 'COG', 'Cracked') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Granite', 'COG', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Granite', 'COG', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Granite', 'COG', 'Seam Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Marble', 'COM', 'Chips') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Marble', 'COM', 'Cracked') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Marble', 'COM', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Marble', 'COM', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Marble', 'COM', 'Seam Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Silestone', 'COU', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Silestone', 'COU', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Solid Surface', 'COS', 'Chips') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Solid Surface', 'COS', 'Cracked') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Solid Surface', 'COS', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Solid Surface', 'COS', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Countertops Solid Surface', 'COS', 'Seam Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Deck', 'DCK', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Deck', 'DCK', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Deck', 'DCK', 'Split Wood') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Deck', 'DCK', 'Warped  ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Drywall', 'DRL', 'Leak Damage') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Drywall', 'DRL', 'One Year') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Drywall', 'DRL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Drywall', 'DRL', 'Settlement') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Drywall', 'DRL', 'Workmanship/Finish') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Electrical', 'ELE', 'Breakers') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Electrical', 'ELE', 'Defective Fixture') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Electrical', 'ELE', 'Doorbell') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Electrical', 'ELE', 'Exterior Lighting') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Electrical', 'ELE', 'Fixture Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Electrical', 'ELE', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Electrical', 'ELE', 'Plugs/Switches') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Electrical', 'ELE', 'Smoke Detectors') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Electrical', 'ELE', 'Wiring') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Doors', 'EXD', 'Broken Seal') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Doors', 'EXD', 'Leak  ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Doors', 'EXD', 'Operation/Adjustment') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Doors', 'EXD', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Doors', 'EXD', 'Reglaze/Scratches') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Trim/Siding', 'EXT', 'Columns') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Trim/Siding', 'EXT', 'Hardi Siding') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Trim/Siding', 'EXT', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Trim/Siding', 'EXT', 'Railings') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Trim/Siding', 'EXT', 'Shutters') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Exterior Trim/Siding', 'EXT', 'Vinyl Siding') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fence', 'FNC', 'Improper Installation') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fence', 'FNC', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fence', 'FNC', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Final Grade', 'GRD', 'Drainage') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Final Grade', 'GRD', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Final Grade', 'GRD', 'Sea Wall') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Final Grade', 'GRD', 'Top Soil') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fire Sprinkler System', 'FSP', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fire Sprinkler System', 'FSP', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fireplace', 'FPL', 'Chimney/Flue/Caps') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fireplace', 'FPL', 'Firebox Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fireplace', 'FPL', 'Firebox Material') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fireplace', 'FPL', 'Mantle') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fireplace', 'FPL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Fireplace', 'FPL', 'Pilot Light') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Flashing', 'FLA', 'Counter Flashing') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Flashing', 'FLA', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Flashing', 'FLA', 'Step Flashing ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Flashing', 'FLA', 'Windows/Doors Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Flatwork', 'FLT', 'Cleaning') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Flatwork', 'FLT', 'Cracks') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Flatwork', 'FLT', 'Finish') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Flatwork', 'FLT', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Flatwork', 'FLT', 'Settlement') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Foundation', 'FND', 'Crawl Space') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Foundation', 'FND', 'Missing Piers') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Foundation', 'FND', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Foundation', 'FND', 'Settlement') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Foundation', 'FND', 'Standing Water') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Foundation', 'FND', 'Underpinning') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Frame Labor', 'FRL', 'Floor Squeaks') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Frame Labor', 'FRL', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Frame Labor', 'FRL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Frame Labor', 'FRL', 'Roof/Decking') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Frame Labor', 'FRL', 'Sub Floor') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Frame Labor', 'FRL', 'Walls') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Front Door', 'FRD', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Front Door', 'FRD', 'Operation/Adjustment') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Front Door', 'FRD', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Garage Door/Opener', 'GAR', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Garage Door/Opener', 'GAR', 'Opener/Remotes') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Garage Door/Opener', 'GAR', 'Operation ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Garage Door/Opener', 'GAR', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Garage Door/Opener', 'GAR', 'Weather Strip') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Gas', 'GLK', 'Appliance Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Gas', 'GLK', 'Fireplace Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Gas', 'GLK', 'Water Heater Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Gas', 'GLK', 'HVAC Equipment Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Gas', 'GLK', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Gutters and Downspouts', 'GUT', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Gutters and Downspouts', 'GUT', 'Leaks') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Gutters and Downspouts', 'GUT', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Gutters and Downspouts', 'GUT', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardware', 'HWR', 'Bath') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardware', 'HWR', 'Door ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardware', 'HWR', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardware', 'HWR', 'Re-Key') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardwood Flooring', 'FHD', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardwood Flooring', 'FHD', 'Joint Separation') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardwood Flooring', 'FHD', 'Leak Damage') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardwood Flooring', 'FHD', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardwood Flooring', 'FHD', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Hardwood Flooring', 'FHD', 'Scratches') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'HBR5', 'HBR5', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Heating/Air Conditioning', 'HVC', 'Balance System') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Heating/Air Conditioning', 'HVC', 'Cooling') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Heating/Air Conditioning', 'HVC', 'Duct Work') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Heating/Air Conditioning', 'HVC', 'Freon/Water Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Heating/Air Conditioning', 'HVC', 'Heat') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Heating/Air Conditioning', 'HVC', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Heating/Air Conditioning', 'HVC', 'Thermostats') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Heating/Air Conditioning', 'HVC', 'Venting/Exhaust') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Accent Furniture') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Accessories') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Area & Stair Rugs') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Case Goods') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Drapery/Bedding/Soft Goods') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Exposed Wood Seating') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Floral') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Lamps') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Upholstery') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Home Furnishings Warranty', 'HFW', 'Wall Art') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Inspection Request', 'ISP', 'Install') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Inspection Request', 'ISP', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Inspection Request', 'ISP', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Insulation', 'INS', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Landscaping Shrubs', 'LND', 'Dead Shrubs') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Landscaping Shrubs', 'LND', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Light Fixtures', 'LGT', 'Broken  ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Light Fixtures', 'LGT', 'Finish') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Light Fixtures', 'LGT', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Light Fixtures', 'LGT', 'Wrong Selection Installed') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Mailbox', 'MLB', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Metal Roof', 'MET', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Metal Roof', 'MET', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Mirrors/Shower Door', 'MIR', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Mirrors/Shower Door', 'MIR', 'Mirrors') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Mirrors/Shower Door', 'MIR', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Mirrors/Shower Door', 'MIR', 'Shower Door Operation') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Paint', 'PNT', 'Ceiling') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Paint', 'PNT', 'Cleaning') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Paint', 'PNT', 'Exterior') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Paint', 'PNT', 'One Year') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Paint', 'PNT', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Paint', 'PNT', 'Stairs') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Paint', 'PNT', 'Trim') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Paint', 'PNT', 'Walls') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pavers', 'Paver', 'Broken') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pavers', 'Paver', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pavers', 'Paver', 'Stained') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pavers', 'Paver', 'Uneven') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pest Control', 'PST', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing', 'PLU', 'Commode') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing', 'PLU', 'Drain/Sewer Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing', 'PLU', 'Fixture Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing', 'PLU', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing', 'PLU', 'Venting ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing', 'PLU', 'Water Heater  ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing', 'PLU', 'Water Supply/Pressure') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing Leaks', 'PLL', 'Commode') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing Leaks', 'PLL', 'Commode Running') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing Leaks', 'PLL', 'Drain') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing Leaks', 'PLL', 'Fixture') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing Leaks', 'PLL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing Leaks', 'PLL', 'Water Heater') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Plumbing Leaks', 'PLL', 'Water Supply ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pool Equipment', 'POL', 'Electric Heater') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pool Equipment', 'POL', 'Electrical Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pool Equipment', 'POL', 'Finish') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pool Equipment', 'POL', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pool Equipment', 'POL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pool Equipment', 'POL', 'Plumbing ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pool Equipment', 'POL', 'Screen Enclosures') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pool Equipment', 'POL', 'Solar Heater') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Pool Equipment', 'POL', 'Tile') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Question', 'QUA', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Retaining Wall', 'RET', 'Crack') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Retaining Wall', 'RET', 'Finish') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Retaining Wall', 'RET', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Retaining Wall', 'RET', 'Settlement/Failure') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Roof', 'ROF', 'Drip Edge') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Roof', 'ROF', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Roof', 'ROF', 'Shingle/Tile') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Roof', 'ROF', 'Vent') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Roof Leak', 'RFL', 'Counter Flashing') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Roof Leak', 'RFL', 'Fireplace') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Roof Leak', 'RFL', 'Flashing') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Roof Leak', 'RFL', 'Other Shingle') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Roof Leak', 'RFL', 'Vent') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Security System', 'SEC', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Septic/Well Equipment', 'SEP', 'Conditioner') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Septic/Well Equipment', 'OCT', 'Electrical Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Septic/Well Equipment', 'NOV', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Septic/Well Equipment', 'DEC', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Septic/Well Equipment', 'JAN', 'Pump') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Skylights', 'SKL', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Skylights', 'SKL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Sod', 'SOD', 'Dead  ') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Sod', 'SOD', 'Missing') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Sod', 'SOD', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Sprinkler System', 'SPL', 'Coverage') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Sprinkler System', 'SPL', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Sprinkler System', 'SPL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Sprinkler System', 'SPL', 'Pressure') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Stairs', 'STA', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Stone Labor & Turnkey', 'SNL', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Stucco', 'STU', 'Finish') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Stucco', 'STU', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Stucco', 'STU', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trees', 'TRE', 'Installed Tree') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trees', 'TRE', 'Original Tree') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trees', 'TRE', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Labor', 'TRL', 'Attic Stairs') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Labor', 'TRL', 'Improper Installation') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Labor', 'TRL', 'Interior Door Adjustment') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Labor', 'TRL', 'Interior Hardware Adjustment') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Labor', 'TRL', 'Missing Trim') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Labor', 'TRL', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Labor', 'TRL', 'Wood Shelving') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Materials/Interior Doors', 'TRM', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Materials/Interior Doors', 'TRM', 'Warped Doors') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Materials/Interior Doors', 'TRM', 'Wrong Door Installed') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Trim Materials/Interior Doors', 'TRM', 'Wrong Trim') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Tub', 'TUB', 'Chips') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Tub', 'TUB', 'Cracked') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Tub', 'TUB', 'Jetterd Operation') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Tub', 'TUB', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Tub', 'TUB', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Vent-A-Hood', 'VEN', 'Installation') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Vent-A-Hood', 'VEN', 'Material Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Vent-A-Hood', 'VEN', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Vinyl', 'VIN', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Vinyl', 'VIN', 'Seam Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Vinyl', 'VIN', 'Torn') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Vinyl', 'VIN', 'Wrong Selection Installed') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Wallpaper', 'WPL', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Water Filtration System', 'WFS', 'Fixture Issue') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Water Filtration System', 'WFS', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Water Filtration System', 'WFS', 'Supply Line and Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Weather Stripping', 'WEA', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Window Treatment', 'WIT', 'All') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Windows', 'WID', 'Broken Seal') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Windows', 'WID', 'Improper Installation') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Windows', 'WID', 'Leak') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Windows', 'WID', 'Operation/Adjustment') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Windows', 'WID', 'Other') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Windows', 'WID', 'Reglaze/Scratches') 
INSERT [dbo].[ProblemCodes] (CategoryCode, JdeCode, DetailCode) VALUES ( 'Windows', 'WID', 'Screens') 
