


delete CityCodeProblemCodeCostCodes where 1=1
GO

INSERT CityCodeProblemCodeCostCodes (CityCodeProblemCodeCostCodeId, CityCode, ProblemJdeCode, CreatedDate, CreatedBy, UpdatedDate, UpdatedBy)

select newid(), max(cities.citycode), ProblemCodes.JdeCode, getdate(), 'manual', getdate(), 'manual'
from cities inner join ProblemCodes on 1=1
where cities.citycode <> ''
group by ProblemCodes.JdeCode, cities.citycode
order by max(cities.citycode), ProblemCodes.JdeCode


update CityCodeProblemCodeCostCodes set CostCode = '2315' WHERE ProblemJdeCode = 'ACD'
update CityCodeProblemCodeCostCodes set CostCode = '4702' WHERE ProblemJdeCode = 'API'
update CityCodeProblemCodeCostCodes set CostCode = '4704' WHERE ProblemJdeCode = 'APP'
update CityCodeProblemCodeCostCodes set CostCode = '4116' WHERE ProblemJdeCode = 'BRL'
update CityCodeProblemCodeCostCodes set CostCode = '3804' WHERE ProblemJdeCode = 'CAB'
update CityCodeProblemCodeCostCodes set CostCode = '3226' WHERE ProblemJdeCode = 'CPH'
update CityCodeProblemCodeCostCodes set CostCode = '5104' WHERE ProblemJdeCode = 'FLC'
update CityCodeProblemCodeCostCodes set CostCode = '5002' WHERE ProblemJdeCode = 'CFN'
update CityCodeProblemCodeCostCodes set CostCode = '3512' WHERE ProblemJdeCode = 'TIL'
update CityCodeProblemCodeCostCodes set CostCode = '3514' WHERE ProblemJdeCode = 'FCT'
update CityCodeProblemCodeCostCodes set CostCode = '3502' WHERE ProblemJdeCode = 'CTW'
update CityCodeProblemCodeCostCodes set CostCode = '2536' WHERE ProblemJdeCode = 'CRL'
update CityCodeProblemCodeCostCodes set CostCode = '3902' WHERE ProblemJdeCode = 'COF'
update CityCodeProblemCodeCostCodes set CostCode = '3904' WHERE ProblemJdeCode = 'COG'
update CityCodeProblemCodeCostCodes set CostCode = '4002' WHERE ProblemJdeCode = 'COM'
update CityCodeProblemCodeCostCodes set CostCode = '3904' WHERE ProblemJdeCode = 'COU'
update CityCodeProblemCodeCostCodes set CostCode = '3904' WHERE ProblemJdeCode = 'COS'
update CityCodeProblemCodeCostCodes set CostCode = '5810' WHERE ProblemJdeCode = 'DCK'
update CityCodeProblemCodeCostCodes set CostCode = '3404' WHERE ProblemJdeCode = 'DRL'
update CityCodeProblemCodeCostCodes set CostCode = '3002' WHERE ProblemJdeCode = 'ELE'
update CityCodeProblemCodeCostCodes set CostCode = '2702' WHERE ProblemJdeCode = 'EXD'
update CityCodeProblemCodeCostCodes set CostCode = '3606' WHERE ProblemJdeCode = 'EXT'
update CityCodeProblemCodeCostCodes set CostCode = '5304' WHERE ProblemJdeCode = 'FNC'
update CityCodeProblemCodeCostCodes set CostCode = '4404' WHERE ProblemJdeCode = 'GRD'
update CityCodeProblemCodeCostCodes set CostCode = '2912' WHERE ProblemJdeCode = 'FSP'
update CityCodeProblemCodeCostCodes set CostCode = '4202' WHERE ProblemJdeCode = 'FPL'
update CityCodeProblemCodeCostCodes set CostCode = '2808' WHERE ProblemJdeCode = 'FLA'
update CityCodeProblemCodeCostCodes set CostCode = '2408' WHERE ProblemJdeCode = 'FLT'
update CityCodeProblemCodeCostCodes set CostCode = '2324' WHERE ProblemJdeCode = 'FND'
update CityCodeProblemCodeCostCodes set CostCode = '2514' WHERE ProblemJdeCode = 'FRL'
update CityCodeProblemCodeCostCodes set CostCode = '2706' WHERE ProblemJdeCode = 'FRD'
update CityCodeProblemCodeCostCodes set CostCode = '5602' WHERE ProblemJdeCode = 'GAR'
update CityCodeProblemCodeCostCodes set CostCode = '2902' WHERE ProblemJdeCode = 'GLK'
update CityCodeProblemCodeCostCodes set CostCode = '5402' WHERE ProblemJdeCode = 'GUT'
update CityCodeProblemCodeCostCodes set CostCode = '3702' WHERE ProblemJdeCode = 'HWR'
update CityCodeProblemCodeCostCodes set CostCode = '5106' WHERE ProblemJdeCode = 'FHD'
update CityCodeProblemCodeCostCodes set CostCode = '3102' WHERE ProblemJdeCode = 'HVC'
update CityCodeProblemCodeCostCodes set CostCode = '3302' WHERE ProblemJdeCode = 'INS'
update CityCodeProblemCodeCostCodes set CostCode = '5808' WHERE ProblemJdeCode = 'LND'
update CityCodeProblemCodeCostCodes set CostCode = '3002' WHERE ProblemJdeCode = 'LGT'
update CityCodeProblemCodeCostCodes set CostCode = '5814' WHERE ProblemJdeCode = 'MLB'
update CityCodeProblemCodeCostCodes set CostCode = '2810' WHERE ProblemJdeCode = 'MET'
update CityCodeProblemCodeCostCodes set CostCode = '4902' WHERE ProblemJdeCode = 'MIR'
update CityCodeProblemCodeCostCodes set CostCode = '4302' WHERE ProblemJdeCode = 'PNT'
update CityCodeProblemCodeCostCodes set CostCode = '5806' WHERE ProblemJdeCode = 'Paver'
update CityCodeProblemCodeCostCodes set CostCode = '2534' WHERE ProblemJdeCode = 'PST'
update CityCodeProblemCodeCostCodes set CostCode = '2902' WHERE ProblemJdeCode = 'PLU'
update CityCodeProblemCodeCostCodes set CostCode = '2902' WHERE ProblemJdeCode = 'PLL'
update CityCodeProblemCodeCostCodes set CostCode = '2218' WHERE ProblemJdeCode = 'RET'
update CityCodeProblemCodeCostCodes set CostCode = '3202' WHERE ProblemJdeCode = 'SEC'
update CityCodeProblemCodeCostCodes set CostCode = '2918' WHERE ProblemJdeCode = 'SEP'
update CityCodeProblemCodeCostCodes set CostCode = '2806' WHERE ProblemJdeCode = 'SKL'
update CityCodeProblemCodeCostCodes set CostCode = '5806' WHERE ProblemJdeCode = 'SOD'
update CityCodeProblemCodeCostCodes set CostCode = '5804' WHERE ProblemJdeCode = 'SPL'
update CityCodeProblemCodeCostCodes set CostCode = '3611' WHERE ProblemJdeCode = 'STA'
update CityCodeProblemCodeCostCodes set CostCode = '4116' WHERE ProblemJdeCode = 'SNL'
update CityCodeProblemCodeCostCodes set CostCode = '4132' WHERE ProblemJdeCode = 'STU'
update CityCodeProblemCodeCostCodes set CostCode = '5802' WHERE ProblemJdeCode = 'TRE'
update CityCodeProblemCodeCostCodes set CostCode = '3606' WHERE ProblemJdeCode = 'TRL'
update CityCodeProblemCodeCostCodes set CostCode = '3602' WHERE ProblemJdeCode = 'TRM'
update CityCodeProblemCodeCostCodes set CostCode = '2902' WHERE ProblemJdeCode = 'TUB'
update CityCodeProblemCodeCostCodes set CostCode = '4702' WHERE ProblemJdeCode = 'VEN'
update CityCodeProblemCodeCostCodes set CostCode = '5102' WHERE ProblemJdeCode = 'VIN'
update CityCodeProblemCodeCostCodes set CostCode = '5202' WHERE ProblemJdeCode = 'WPL'
update CityCodeProblemCodeCostCodes set CostCode = '2910' WHERE ProblemJdeCode = 'WFS'
update CityCodeProblemCodeCostCodes set CostCode = '5902' WHERE ProblemJdeCode = 'WIT'
update CityCodeProblemCodeCostCodes set CostCode = '2602' WHERE ProblemJdeCode = 'WID'
