ALTER TABLE Cities ADD PurchaseOrderMaxAmount decimal (18,2) NULL
GO

UPDATE Cities SET PurchaseOrderMaxAmount = 1500 WHERE CityCode = 'ATL'
UPDATE Cities SET PurchaseOrderMaxAmount = 1000 WHERE CityCode = 'AUS'
UPDATE Cities SET PurchaseOrderMaxAmount = 600 WHERE CityCode = 'CHA'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'CHI'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'COR'
UPDATE Cities SET PurchaseOrderMaxAmount = 800 WHERE CityCode = 'CSC'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'CTX'
UPDATE Cities SET PurchaseOrderMaxAmount = 300 WHERE CityCode = 'DAL'
UPDATE Cities SET PurchaseOrderMaxAmount = 250 WHERE CityCode = 'DEN'
UPDATE Cities SET PurchaseOrderMaxAmount = 1000 WHERE CityCode = 'FTM'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'HIL'
UPDATE Cities SET PurchaseOrderMaxAmount = 200 WHERE CityCode = 'HOU'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'IND'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'JAC'
UPDATE Cities SET PurchaseOrderMaxAmount = 500 WHERE CityCode = 'NAS'
UPDATE Cities SET PurchaseOrderMaxAmount = 300 WHERE CityCode = 'ORL'
UPDATE Cities SET PurchaseOrderMaxAmount = 500 WHERE CityCode = 'PAN'
UPDATE Cities SET PurchaseOrderMaxAmount = 1000 WHERE CityCode = 'PHX'
UPDATE Cities SET PurchaseOrderMaxAmount = 500 WHERE CityCode = 'RAL'
UPDATE Cities SET PurchaseOrderMaxAmount = 350 WHERE CityCode = 'SAN'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'SLC'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'SPE'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'TAL'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'TAM'
UPDATE Cities SET PurchaseOrderMaxAmount = 99999 WHERE CityCode = 'TUL'
