BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE [{{DatabaseName}}_NServicebus].[dbo].[HEALTH_Showcase]
	(
	JobNumber varchar(8) NOT NULL,
	System int NOT NULL
	)  ON [PRIMARY]
GO
COMMIT
