namespace Warranty.LotusExtract.Columns
{
    public static class CustomerColumns
    {
        public static int Address = 0;
        public static int Area = 1;
        public static int AreaPresidentCode = 2;
        public static int Attachments = 3;
        public static int BuildNumber = 4;
        public static int Breaks = 5;
        public static int Builder = 6;
        public static int BuilderEmployeeNumber = 7;
        public static int City = 8;
        public static int CityCode = 9;
        public static int CityShortCode = 10;
        public static int CloseDate = 11;
        public static int Community = 12;
        public static int CommunityNumber = 13;
        public static int Coversheets = 14;
        public static int DateConverted = 15;
        public static int DivisionCode = 16;
        public static int Division = 17;
        //public static int DNC = 18; /* No data in extract */
        public static int DocumentAuthor = 19;
        public static int Elevation = 20;
        public static int EmailContact = 21;
        public static int HomeOwner = 22;
        public static int HomeOwnerMoved = 23;
        public static int HomePhone = 24;
        public static int JobNumber = 25;
        public static int LastModified = 26;
        public static int LegalDescription = 27;
        public static int ModifiedBy = 28;
        public static int Options = 29;
        public static int OtherPhone = 30;
        public static int OwnerNumber = 31;
        public static int Plan = 32;
        public static int PlanType = 33;
        public static int PlanTypeDescription = 34;
        public static int PlanName = 35;
        public static int PreviousOwner1 = 36;
        public static int PreviousOwner2 = 37;
        public static int PreviousOwner3 = 38;
        public static int PrintedName = 39;
        public static int Processed = 40;
        public static int Project = 41;
        public static int ProjectCode = 42;
        public static int SalesConsultantNumber = 43;
        public static int SalesConsultant = 44;
        public static int SateliteCode = 45;
        public static int SelectionSheets = 46;
        public static int State = 47;
        public static int Swing = 48;
        public static int TotalSalesPrice = 49;
        public static int UnitNumber = 50;
        public static int WarrantyExpirationDate = 51;
        //public static int Warr_IC = 52; /* No data in extract */
        public static int WorkPhone1 = 53;
        public static int WorkPhone2 = 54;
        public static int ZipCode = 55;
        //public static int Column_01 = 56; /* Same as ordinal 9 */
        //public static int Column_02 = 57; /* Same as ordinal 12 */
        //public static int Address_2 = 58; /* Same as ordinal 1 */
        //public static int Home_Owner = 59; /* Same as ordinal 22*/
        //public static int Close_Date_2 = 60; /* Same as ordinal 11*/
        //public static int Job_# = 61; /* Same as ordinal 25*/
        public static int FileNames = 62;
    }
}